### ISSUE TITLE
sample Jython script only enable/disable statisitcs on specified pmimodules (was 8.5)

### ISSUE THREAD

**Issue by toni-moreno** [yannlambret/websphere-graphite#1]
I After testing this tool We are notice that we are only configuring the listed pmimodules in "stats"
```
# PMI statistics values
stats = { 'jvmRuntimeModule': '1,3,5',
          'threadPoolModule': '3,4,8',
          'transactionModule': '4',
          'connectionPoolModule': '5,6,7',
          'j2cModule': '5,6,7',
          'servletSessionsModule': '7',
          'webAppModule': '13' }
```

All other pmimodules maintains all its stats enabled ( which is not the desirable behavior for me).

how can I disable all stats before setting the custom modules?

**Comment by yannlambret** [comment]
Hello Toni,

I don't know why WebSphere 8.5 behaves in this way. The only workaround I see is to "reset" the PMI configuration just before setting it, something like:

```python
params = [['enable', 'false'], ['statisticSet', 'none']]
AdminConfig.modify(pmi_service, params)
AdminConfig.save()

params = [['enable', 'true'], ['statisticSet', 'custom']]
AdminConfig.modify(pmi_service, params)
```

Hope this helps.
